name: build

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu', 'windows']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive' 
      - name: build
        run: ./ci/ci.bash
        shell: bash
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: godot-pure-data-${{ matrix.os }}
          path: work/install
  
  package:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download all build artifacts
        uses: actions/download-artifact@v2
        with:
          path: work/artifacts
      - name: build
        run: sh ci/package.bash work/artifacts
        shell: bash
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: project
          path: addons

  publish:
    needs: [package]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: download all build artifacts
        uses: actions/download-artifact@v2
        with:
          name: project
          path: addons
      - name: compress release
        run: |
          mkdir dist
          tar -czvf dist/godot-pure-data-universal.tar.gz addons
      - name: create release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: dist/*
          fail_on_unmatched_files: true

  remove-old-artifacts:
    needs: [publish]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: remove-old-artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '10 minutes'
